reorganized content in ts and FAQs section and added new CICS questions
IBM/z_ansible_collections_doc pull request #21
Opened 2021-08-24 06:06 UTC by RadhaV2020

Signed-off-by: RadhaV2020 <63616898+RadhaV2020@users.noreply.github.com>

2021-08-24 06:17 UTC, RadhaV2020 commented
Some minor issues with hyperlinks exist in this PR. Will be fixed in the next commit

2021-08-24 22:20 UTC, RadhaV2020 commented
fixed the hyperlink issues, moved the CICS troubleshooting question under the TS section per the CICS team's ask.

2021-09-03 00:33 UTC, itsBryantP requested changes

2021-09-03 00:33 UTC, itsBryantP commented on source/Troubleshooting/errorsandmessages.rst
> +  * `IBM z/OS core <https://github.com/ansible-collections/ibm_zos_core/issues/new/choose>`_
update to include references to all collections that are part of RHACCIZ

2021-09-03 00:33 UTC, itsBryantP commented on source/faqs/faqs.rst
> +* `IBM z/OS core <https://github.com/ansible-collections/ibm_zos_core/issues/new/choose>`_
update to include references to all collections that are part of RHACCIZ

2021-09-03 17:15 UTC, itsBryantP approved these changes

2021-09-03 17:26 UTC, merged